# Generated by Django 3.1.5 on 2021-08-27 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='first_name',
            new_name='Adınız',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='Mesajınız',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='last_name',
            new_name='Soyadınız',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='Telefonunuz',
        ),
    ]
